[2025-07-16T15:36:39.615+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T15:36:39.649+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_s3.bash_task manual__2025-07-16T15:36:35.472822+00:00 [queued]>
[2025-07-16T15:36:39.666+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_s3.bash_task manual__2025-07-16T15:36:35.472822+00:00 [queued]>
[2025-07-16T15:36:39.675+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-07-16T15:36:39.698+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): bash_task> on 2025-07-16 15:36:35.472822+00:00
[2025-07-16T15:36:39.710+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_s3', 'bash_task', 'manual__2025-07-16T15:36:35.472822+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_s3.py', '--cfg-path', '/tmp/tmp24_0g815']
[2025-07-16T15:36:39.713+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask bash_task
[2025-07-16T15:36:39.715+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3147) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T15:36:39.716+0000] {standard_task_runner.py:72} INFO - Started process 3148 to run task
[2025-07-16T15:36:39.782+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_s3.bash_task manual__2025-07-16T15:36:35.472822+00:00 [running]> on host 4461bcf72552
[2025-07-16T15:36:40.127+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_s3' AIRFLOW_CTX_TASK_ID='bash_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T15:36:35.472822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-16T15:36:35.472822+00:00'
[2025-07-16T15:36:40.128+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-16T15:36:40.150+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-16T15:36:40.153+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "S3 Key exists!"']
[2025-07-16T15:36:40.170+0000] {subprocess.py:99} INFO - Output:
[2025-07-16T15:36:40.176+0000] {subprocess.py:106} INFO - S3 Key exists!
[2025-07-16T15:36:40.177+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-07-16T15:36:40.215+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-16T15:36:40.216+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_s3, task_id=bash_task, run_id=manual__2025-07-16T15:36:35.472822+00:00, execution_date=20250716T153635, start_date=20250716T153639, end_date=20250716T153640
[2025-07-16T15:36:40.253+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-16T15:36:40.278+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T15:36:40.286+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
