[2025-07-16T15:36:36.892+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T15:36:36.917+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_s3.s3_key_sensor manual__2025-07-16T15:36:35.472822+00:00 [queued]>
[2025-07-16T15:36:36.930+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_s3.s3_key_sensor manual__2025-07-16T15:36:35.472822+00:00 [queued]>
[2025-07-16T15:36:36.938+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-07-16T15:36:36.958+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): s3_key_sensor> on 2025-07-16 15:36:35.472822+00:00
[2025-07-16T15:36:36.972+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_s3', 's3_key_sensor', 'manual__2025-07-16T15:36:35.472822+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dag_s3.py', '--cfg-path', '/tmp/tmp81dy9irk']
[2025-07-16T15:36:36.976+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask s3_key_sensor
[2025-07-16T15:36:36.978+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3132) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T15:36:36.979+0000] {standard_task_runner.py:72} INFO - Started process 3145 to run task
[2025-07-16T15:36:37.042+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_s3.s3_key_sensor manual__2025-07-16T15:36:35.472822+00:00 [running]> on host 4461bcf72552
[2025-07-16T15:36:37.480+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_s3' AIRFLOW_CTX_TASK_ID='s3_key_sensor' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T15:36:35.472822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-16T15:36:35.472822+00:00'
[2025-07-16T15:36:37.481+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-16T15:36:37.504+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-07-16T15:36:37.505+0000] {s3.py:116} INFO - Poking for key : s3://***/test.csv
[2025-07-16T15:36:37.521+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-07-16T15:36:37.522+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-07-16T15:36:38.155+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-07-16T15:36:38.169+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-16T15:36:38.170+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_s3, task_id=s3_key_sensor, run_id=manual__2025-07-16T15:36:35.472822+00:00, execution_date=20250716T153635, start_date=20250716T153636, end_date=20250716T153638
[2025-07-16T15:36:38.239+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-16T15:36:38.278+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-16T15:36:38.309+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
